#!/bin/python3

import sys, math

def revisedRussianRoulette(doors):
    # Complete this function
    retsmall = 0
    retbig = 0
    res = {}
    temp = 0
    for i in range(len(doors)):
        if doors[i] == 1:
            temp += 1
        else:
            if temp in res:
                res[temp] = res[temp] + 1
            else:
                res[temp] = 1
            temp = 0
    if temp in res:
        res[temp] = res[temp] + 1
    else:
        res[temp] = 1
    temp = 0
    
    for key, value in res.items():
        if key != 0:
            retsmall += math.ceil(key / 2) * value
            retbig += key * value
    # print(res)
    return [retsmall, retbig]
        

if __name__ == "__main__":
    n = int(input().strip())
    doors = list(map(int, input().strip().split(' ')))
    result = revisedRussianRoulette(doors)
    print (" ".join(map(str, result)))
